version: "3"

vars:
  base_cmd: "npm"  # Change this as needed to "go", "bundle", "pip", etc.

tasks:
  default:
    desc: "Run a command with the specified tool"
    cmds:
      - docker compose run --rm {{.base_cmd}} {{.CLI_ARGS}}
    silent: true

  up:
    desc: "Start the application in development mode"
    cmds:
      - docker compose watch

  down:
    desc: "Stop and remove all containers, networks"
    cmds:
      - docker compose down

  lint:
    desc: "Run linting"
    cmds:
      - docker compose run --rm npm run lint

  test:
    desc: "Run unit tests"
    cmds:
      - docker compose run --rm npm run test

  build:
    desc: "Build the Docker image(s)"
    cmds:
      - docker compose build
