on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .gitignore
      - Brewfile
      - README.md
    branches:
      - main

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write
  deployments: write

name: Deployment

# We can't use the environment keyword here because it doesn't
# give us control to show the deployment status as ArgoCD rolls out the changes.
# This will still block the next job from running if the production environment has rules set up.
jobs:
  production:
    name: Production
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: production

  sandbox:
    needs: production
    name: Sandbox
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: sandbox

  build:
    needs: sandbox
    name: Image
    uses: gitops-ci-cd/.github/.github/workflows/build.yaml@main

  release:
    needs: build
    name: GitHub
    uses: gitops-ci-cd/.github/.github/workflows/release.yaml@main
