on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .gitignore
      - Brewfile
      - README.md
    branches:
      - main

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write
  deployments: write

name: Production Deployment

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitops-ci-cd/.github/actions/release@main
        with:
          sha: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: gitops-ci-cd/.github/actions/build@main

  deploy_sandbox:
    needs: build
    environment: sandbox
    runs-on: ubuntu-latest
