on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .gitignore
      - Brewfile
      - README.md
    branches:
      - main

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write
  deployments: write

name: Production Deployment

# We can't use the environment keyword here because it doesn't
# give us control to show the deployment status as ArgoCD rolls out the changes.
# This will still block the next job from running if the production environment has rules set up.
jobs:
  deploy_production:
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: production

  deploy_sandbox:
    needs: deploy_production
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: sandbox

  build:
    needs: deploy_production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitops-ci-cd/.github/actions/release@main
        with:
          sha: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: gitops-ci-cd/.github/actions/build@main
