on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .gitignore
      - Brewfile
      - README.md
    branches:
      - main

name: Production Deployment

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitops-ci-cd/.github/actions/release@main
        with:
          sha: ${{ github.sha }}
      - uses: gitops-ci-cd/.github/actions/build@main

  deploy_production:
    permissions:
      deployments: write
    needs: build
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: production

  deploy_sandbox:
    permissions:
      deployments: write
    needs: build
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: sandbox
