on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .gitignore
      - Brewfile
      - README.md
    branches:
      - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  deployments: write

name: Production Deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: checkout@v4
      - uses: gitops-ci-cd/.github/actions/release@main
        with:
          sha: ${{ github.sha }}
      - uses: gitops-ci-cd/.github/actions/build@main

  deploy_production:
    needs: build
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: production

  deploy_sandbox:
    needs: build
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: sandbox
