name: Release Workflow

on:
  release:
    types: [published]

jobs:
  update_image_sha_and_deploy:
    # Run only if NOT a pre-release
    if: ${{ github.event.release.prerelease == false }}
    name: Update Image SHA and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitHub Deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            console.log("CONTEXT")
            console.log(context)
            let response = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.github.sha,
              description: 'Deploying to production...'
            });
            console.log(`Deployment created with ID: ${response.data.id}`);

            response = await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: response.data.id,
              state: 'success',
              environment_url: `https://acme.inc`,
              description: 'Production environment deployed successfully!',
            });
