name: Release Workflow

on:
  release:
    types: [published]

jobs:
  update_image_sha_and_deploy:
    # Run only if NOT a pre-release
    if: ${{ github.event.release.prerelease == false }}
    name: Update Image SHA and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Trigger GitHub Deployment
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.github.sha,
              description: 'Deploying to production'
            });
            console.log(`Deployment created with ID: ${response.data.id}`);
