on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .gitignore
      - Brewfile
      - README.md
    branches:
      - main

permissions:
  contents: write

name: Tag Repository

jobs:
  tag:
    uses: gitops-ci-cd/.github/.github/workflows/tag.yaml@main
