name: Ephemeral Environment Workflow

on:
  pull_request:
    types:
      - labeled

jobs:
  spin_up_deployment:
    if: github.event.label.name == 'ephemeral'
    name: Spin Up Ephemeral Environment
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Trigger GitHub Deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            let response = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.ref,
              required_contexts: [],
              environment: 'ephemeral',
              description: 'Spinning up ephemeral environment...',
              transient_environment: true,
            });
            console.log(`Deployment created with ID: ${response.data.id}`);

            response = await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: response.data.id,
              state: 'success',
              environment_url: `https://${context.payload.pull_request.head.ref}.acme.inc`,
              description: 'Ephemeral environment is live!',
            });
