name: Ephemeral Environment Workflow

on:
  pull_request:
    types:
      - unlabeled

jobs:
  tear_down_deployment:
    if: github.event.label.name == 'ephemeral'
    name: Tear Down Ephemeral Environment
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Deployment Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            console.log("PAYLOAD");
            console.log(context.payload);
            let response = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.ref,
            });

            if (!response.data) {
              console.log('No deployments found!');
              return;
            }

            response = await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: response.data[0].id,
              state: 'inactive',
              description: 'Ephemeral environment terminated.',
            });
