name: Preview Environment Workflow

on:
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  spin_up_deployment:
    if: github.event.action == 'labeled' && github.event.label.name == 'preview' || github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'preview')
    name: Spin Up Preview Environment
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitHub Deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            let response = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.ref,
              required_contexts: [],
              environment: 'preview',
              description: 'Deploying to preview environment...',
              transient_environment: true,
            });
            console.log(`Deployment created with ID: ${response.data.id}`);

            response = await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: response.data.id,
              state: 'success',
              environment_url: `https://${context.payload.pull_request.head.ref}.acme.inc`,
              description: 'Preview environment deployed successfully!',
            });
